apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
spec:
  exporter:
    endpoint: http://collector-xray-collector:4317
  java:
    image: public.ecr.aws/aws-observability/adot-autoinstrumentation-java:v1.31.1
