apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-xray-spring-boot-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-xray-spring-boot-sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-xray-spring-boot-sample
    spec:
      containers:
        - name: aws-xray-spring-boot-sample
          image: 748487307014.dkr.ecr.eu-central-1.amazonaws.com/samples/aws-xray-spring-boot-sample:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: "xray-service:2000"
